name: Releases

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Release
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        name: KOT ${{ github.ref_name }}
        generateReleaseNotes: true
        token: ${{ secrets.ONUR_TOKEN }}
